### Notifikasi
GET http://localhost:3000/notifikasi/

### Create Notifikasi
POST http://localhost:3000/notifikasi/
Content-Type: application/json

{
    "reqId": "req-001",
    "userId": 1,
    "title": "Notifikasi 1",
    "message": "Ini merupakan notifikasi 1",
    "isRead": false
}

### Update Notifikasi
PUT http://localhost:3000/notifikasi/62ab394e577af341168129fb

{
    "reqId": "req-002",
    "userId": 1,
    "title": "Notifikasi 4",
    "message": "Ini merupakan notifikasi 4",
    "isRead": false,
}

### login
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "admin",
}